version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: aban
      POSTGRES_USER: aban
      POSTGRES_PASSWORD: abanpass

  redis:
    image: "redis:latest"

  web:
    build: .
    command: >
      sh -c "python manage.py test"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
